name: stream
version: 2.6.0
description: > 
  Lightweight Dart web server supporting request routing, filtering,
  template engine, MVC design pattern, and file-based static resources.
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream
repository: https://github.com/rikulo/stream
issue_tracker: https://github.com/rikulo/stream/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rikulo_commons: ^5.0.0
  logging: ^1.0.1
  args: ^2.0.0
  path: ^1.8.0
  http: ^0.13.1
  charcode: ^1.2.0

executables:
  rspc:
