name: stream
version: 2.0.1
description: > 
  Lightweight Dart web server supporting request routing, filtering,
  template engine, MVC design pattern, and file-based static resources.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: http://rikulo.org/projects/stream
documentation: http://docs.rikulo.org/stream
dependencies:
  rikulo_commons: any
  logging: any
  args: any
  path: any
  http: any
  charcode: any

environment:
  sdk: '>=2.0.0-dev <3.0.0'
